/** Curated Lucide icon names suitable for keycap legends (v1). */
export const KEYCAP_ICON_NAMES = [
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "ChevronUp",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "CornerDownLeft",
  "Delete",
  "Eraser",
  "Space",
  "Command",
  "Option",
  "Play",
  "Pause",
  "SkipBack",
  "SkipForward",
  "Volume2",
  "VolumeX",
  "Mic",
  "MicOff",
  "Sun",
  "Moon",
  "Power",
  "Home",
  "Search",
  "Settings",
  "Menu",
  "Plus",
  "Minus",
  "X",
  "Check",
  "Star",
  "Heart",
  "Music",
  "Camera",
  "Bluetooth",
  "Wifi",
  "Battery",
] as const

export type KeycapIconName = (typeof KEYCAP_ICON_NAMES)[number]
